language: generic

sudo: required

services:
  - docker

env:
  - BUILD=ubuntu
  - BUILD=centos

script:
  - "docker-compose build $BUILD"

notifications:
  email:
    - collins.christopher@gmail.com
    - alexander.t.merck@gmail.com
