---
  pkgs:
    - git
    - python-virtualenv

  wordpot_repo: https://github.com/threatstream/wordpot.git

  wordpot_dir: /opt/wordpot
  wordpot_user: wordpot

  runit_service_dir: /etc/service/wordpot
